using System.Text.RegularExpressions;
using System.Xml.Linq;
using Sedna.UI.Tests.TestSupport;

namespace Sedna.UI.Tests;

/// <summary>
/// The stylesheet, the script and the token export are generated and committed, so each can drift from its source.
/// </summary>
public class GeneratedArtefactTests
{
    [Fact]
    public void The_token_export_matches_the_stylesheet()
    {
        // wwwroot/tokens/Sedna.UI.tokens.json is the token contract for consumers
        // that are not CSS — a Figma import, a report generator picking chart colours,
        // a contrast audit. Generated by build/export-tokens.sh, committed like the
        // other two generated assets, and therefore able to drift.
        //
        // Checked as invariants rather than by re-running the generator in C#: every
        // token declared anywhere in the sheet appears in the export with the same
        // value, and the export invents nothing.
        var exportPath = Path.Combine(Assets.ProjectDir, "wwwroot", "tokens", "Sedna.UI.tokens.json");
        Assert.True(File.Exists(exportPath),
            $"No token export at {exportPath}. Run build/export-tokens.sh");

        using var doc = System.Text.Json.JsonDocument.Parse(File.ReadAllText(exportPath));

        var exported = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var block in doc.RootElement.GetProperty("blocks").EnumerateArray())
            foreach (var token in block.GetProperty("tokens").EnumerateObject())
            {
                if (!exported.TryGetValue(token.Name, out var values))
                    exported[token.Name] = values = new HashSet<string>(StringComparer.Ordinal);
                values.Add(Assets.Squash(token.Value.GetString() ?? string.Empty));
            }

        var css = Assets.StripComments(Assets.Css);

        // Every declaration in a token block, as name → the set of values it takes
        // across the themes. Compared as sets, because a token legitimately has one
        // value per theme.
        var declared = new Dictionary<string, HashSet<string>>(StringComparer.Ordinal);
        foreach (var (_, body) in Assets.TokenBlocks(css))
            foreach (var declaration in body.Split(';', StringSplitOptions.TrimEntries))
            {
                if (!declaration.StartsWith("--", StringComparison.Ordinal)) continue;
                var colon = declaration.IndexOf(':', StringComparison.Ordinal);
                if (colon <= 0) continue;

                var name = declaration[..colon].Trim();
                var value = Assets.Squash(declaration[(colon + 1)..].Trim());
                if (!declared.TryGetValue(name, out var values))
                    declared[name] = values = new HashSet<string>(StringComparer.Ordinal);
                values.Add(value);
            }

        var problems = new List<string>();

        foreach (var (name, values) in declared.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            if (!exported.TryGetValue(name, out var got))
            {
                problems.Add($"{name} is in the stylesheet but not in the export");
                continue;
            }

            foreach (var missing in values.Except(got, StringComparer.Ordinal))
                problems.Add($"{name} = \"{missing}\" is in the stylesheet but not in the export");
        }

        foreach (var name in exported.Keys.Except(declared.Keys, StringComparer.Ordinal)
                     .OrderBy(n => n, StringComparer.Ordinal))
            problems.Add($"{name} is in the export but declared nowhere in the stylesheet");

        Assert.True(problems.Count == 0,
            $"Run build/export-tokens.sh:{Environment.NewLine}{string.Join(Environment.NewLine, problems)}");
    }

    [Fact]
    public void The_shipped_script_matches_its_parts()
        => AssertBundleMatchesParts("js-parts", "*.js", Assets.JsPath, "build/bundle-js.sh");

    [Fact]
    public void The_shipped_stylesheet_matches_its_parts()
        => AssertBundleMatchesParts("css-parts", "*.css", Assets.CssPath, "build/bundle-css.sh");

    /// <summary>
    /// Both shipped assets are generated by concatenating a directory of parts. The
    /// checks are invariants rather than a re-implementation of the generator's
    /// header formatting — two copies of the same formatting would drift against
    /// each other and fail for cosmetic reasons.
    /// </summary>
    private static void AssertBundleMatchesParts(
        string partsDirName, string pattern, string bundlePath, string script)
    {
        // Both assets are committed in generated form so a plain checkout, the
        // catalogue and the package all work with no build step. That makes drift
        // possible, which is what this guards: edit a part, forget the script, and the
        // two disagree silently — every consuming app would keep the old behaviour.
        //
        // The .NET SDK cannot generate either for us. Its only CSS bundling is scoped
        // .razor.css, which rewrites selectors and would scope tier-2 classes to markup
        // the library renders; it does nothing at all for a global script.
        //
        // Ordinal ordering matches LC_ALL=C in the scripts, so the same bytes come out
        // on Windows and on the Linux CI runner.
        var partsDir = Path.Combine(Assets.ProjectDir, partsDirName);
        Assert.True(Directory.Exists(partsDir), $"No {partsDirName} directory at {partsDir}");

        var parts = Directory.GetFiles(partsDir, pattern)
            .OrderBy(p => Path.GetFileName(p), StringComparer.Ordinal)
            .ToList();

        Assert.True(parts.Count > 0, $"No parts found in {partsDir}");

        var bundle = File.ReadAllText(bundlePath);
        var problems = new List<string>();

        // Checked as invariants rather than by re-implementing the generator's header
        // in C#: two copies of the same formatting would drift against each other and
        // the test would start failing for cosmetic reasons.

        // 1. Ordering is the filename order, so every part needs a numeric prefix.
        foreach (var name in parts.Select(Path.GetFileName))
            if (name is null || !Regex.IsMatch(name, @"^\d\d-"))
                problems.Add($"{name} has no NN- prefix, so its position in the build is undefined");

        // 2. Every part's exact text is present, and in the same order — that is what
        //    makes the single file equivalent to the parts.
        var cursor = 0;
        foreach (var part in parts)
        {
            var text = File.ReadAllText(part);
            var at = bundle.IndexOf(text, cursor, StringComparison.Ordinal);
            if (at < 0)
            {
                problems.Add($"{Path.GetFileName(part)} is missing from the bundle, or appears out of order");
                break;
            }

            cursor = at + text.Length;
        }

        // 3. The generated contents block lists exactly the directory, so a part can
        //    never be silently absent from the build.
        var ext = Regex.Escape(Path.GetExtension(pattern));
        var listed = Regex.Matches(bundle, @"^\s{5}(\d\d-[a-z0-9-]+" + ext + @")\s*$", RegexOptions.Multiline)
            .Select(m => m.Groups[1].Value)
            .ToList();
        var expectedNames = parts.Select(Path.GetFileName).ToList();
        if (!listed.SequenceEqual(expectedNames, StringComparer.Ordinal))
            problems.Add(
                $"the generated contents block lists [{string.Join(", ", listed)}] but {partsDirName}/ holds " +
                $"[{string.Join(", ", expectedNames)}]");

        Assert.True(problems.Count == 0,
            $"{Path.GetFileName(bundlePath)} is out of step with {partsDirName}/. Run {script}:" +
            $"{Environment.NewLine}{string.Join(Environment.NewLine, problems)}");
    }
}
