using System.Text.Json;
using Sedna.UI.Catalogue.Navigation;

namespace Sedna.UI.Catalogue.Mcp;

/// <summary>
/// The class history as it stood at the latest release: the copy
/// <c>release.yml</c> generates at the tag and attaches to the GitHub release.
/// </summary>
/// <remarks>
/// <para>
/// The embedded <c>class-history.json</c> is regenerated by the first pull request
/// after a release, so between the tag and that merge every entry the release
/// shipped still reads <c>null</c> there — "in no release", which warns an agent off
/// things its pinned version has. This copy was generated at the tag with the tag
/// present, so it is exact in both directions: an entry it dates is in that release,
/// and an entry merged after the tag is not in it at all.
/// </para>
/// <para>
/// <see cref="VersionEnvelope"/> takes a version from here only where the embedded
/// copy says <c>null</c>. Nothing else reads it, and a fetch that fails leaves the
/// embedded copy in charge — the state the site was in before this existed, and the
/// safe direction: it under-reports what a version has, never over-reports.
/// </para>
/// </remarks>
internal sealed class ReleasedHistory
{
    /// <summary>Where the latest release's copy lives. Configuration <c>ReleasedHistory:Url</c>
    /// overrides it, and an empty value turns the fetch off — which the tests do.</summary>
    public const string DefaultUrl = CatalogueLinks.Releases + "/latest/download/class-history.json";

    private volatile HistoryMaps? _current;

    /// <summary>The latest release's maps, or null until they have been fetched.</summary>
    public HistoryMaps? Current => _current;

    internal void Set(HistoryMaps? maps) => _current = maps;
}

/// <summary>Fetches the latest release's class history at startup and every hour after.</summary>
internal sealed class ReleasedHistoryFetcher(
    ReleasedHistory target,
    IConfiguration configuration,
    ILogger<ReleasedHistoryFetcher> log) : BackgroundService
{
    private static readonly TimeSpan Every = TimeSpan.FromHours(1);

    protected override async Task ExecuteAsync(CancellationToken stopping)
    {
        var url = configuration["ReleasedHistory:Url"] ?? ReleasedHistory.DefaultUrl;
        if (string.IsNullOrWhiteSpace(url)) return;

        using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(15) };
        http.DefaultRequestHeaders.UserAgent.ParseAdd("Sedna.UI.Catalogue");

        while (!stopping.IsCancellationRequested)
        {
            try
            {
                await using var stream = await http.GetStreamAsync(url, stopping);
                using var document = await JsonDocument.ParseAsync(stream, cancellationToken: stopping);
                var maps = HistoryMaps.Parse(document.RootElement);
                target.Set(maps);
                log.LogInformation("Class history of release {Release} loaded from {Url}.", maps.LatestRelease, url);
            }
            catch (OperationCanceledException) when (stopping.IsCancellationRequested)
            {
                return;
            }
            catch (Exception ex)
            {
                // Logged in one line, never thrown: the embedded copy stays in charge, and
                // a release with no asset yet is a 404 every hour, not a stack trace.
                log.LogWarning("The released class history could not be fetched from {Url}: {Reason}", url, ex.Message);
            }

            try
            {
                await Task.Delay(Every, stopping);
            }
            catch (OperationCanceledException)
            {
                return;
            }
        }
    }
}
